name: dynamic_widget_builder
description: A Flutter package to dynamically build widgets from JSON descriptions.
version: 0.0.1
homepage: https://github.com/ahmedkameelha/widgety_builder.git # Replace with your repository URL

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  xml: ^6.2.0
  json_annotation: ^4.4.0
  build_runner: ^2.1.4
  json_serializable: ^6.1.5
  xml2json: ^5.3.2
  url_launcher: ^6.3.0
  flutter_secure_storage: ^5.0.2
  webview_flutter: ^4.2.2
  flutter_cache_manager: ^3.2.0  # Compatible with file ^6.0.0
  share_plus: ^6.0.0  # Keep share_plus as it is required by dynamic_widget_builder
  
dependency_overrides:
  image_picker: ^0.8.7+4
  file: ^6.0.0  # Ensure compatibility with share_plus ^6.0.0 and flutter_cache_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
